# Generated by Django 4.0.6 on 2022-07-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkuser',
            old_name='room',
            new_name='is_online',
        ),
    ]
